/**
 * Concatenates the migrations and seed into one pasteable SETUP.sql.
 *
 *   node supabase/build-setup.mjs
 *
 * Edit the source files, never SETUP.sql — it is regenerated.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

const FILES = [
  'migrations/0001_init.sql',
  'migrations/0002_storage.sql',
  'seed.sql',
  'migrations/0003_urdu.sql',
  'migrations/0004_fix_admin_bootstrap.sql',
  'migrations/0005_stats_counts.sql',
  'migrations/0006_school_fees_and_budget.sql',
  'migrations/0007_bank_details.sql',
  'migrations/0008_transfer_receipts.sql',
  'migrations/0009_recurring_monthly.sql',
  'migrations/0010_donors.sql',
];

const header = `-- =====================================================================
-- Subaidar Hasnain Foundation — COMPLETE SETUP
--
-- Paste this whole file into Supabase → SQL Editor → Run.
-- It is idempotent: safe to run again after a change.
--
-- Combines, in order:
${FILES.map((f) => `--   ${f}`).join('\n')}
-- Generated by supabase/build-setup.mjs — edit the source files, not this one.
-- =====================================================================

`;

const body = FILES.map(
  (f) =>
    `\n\n-- ####################  ${f}  ####################\n\n` +
    readFileSync(resolve(here, f), 'utf8')
).join('');

writeFileSync(resolve(here, 'SETUP.sql'), header + body, 'utf8');
console.log(`SETUP.sql written — ${(header + body).split('\n').length} lines`);
