-- =====================================================================
-- Subaidar Hasnain Foundation — COMPLETE SETUP
--
-- Paste this whole file into Supabase → SQL Editor → Run.
-- It is idempotent: safe to run again after a change.
--
-- Combines, in order:
--   migrations/0001_init.sql
--   migrations/0002_storage.sql
--   seed.sql
--   migrations/0003_urdu.sql
--   migrations/0004_fix_admin_bootstrap.sql
--   migrations/0005_stats_counts.sql
--   migrations/0006_school_fees_and_budget.sql
-- Generated by supabase/build-setup.mjs — edit the source files, not this one.
-- =====================================================================



-- ####################  migrations/0001_init.sql  ####################

-- ===========================================================================
-- Subaidar Hasnain Foundation — core schema
-- Run in Supabase → SQL Editor (or `supabase db push`).
-- ===========================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin
  create type gender_t as enum ('male', 'female', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  -- The four stages the member sees, plus a terminal 'rejected'.
  create type request_status as enum ('requested', 'review', 'accepted', 'transferred', 'rejected');
exception when duplicate_object then null; end $$;

do $$ begin
  create type user_role as enum ('member', 'admin');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- profiles — one row per auth user, holds the registration details
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  full_name    text        not null,
  gender       gender_t    not null,
  age          int         not null check (age between 12 and 120),
  country      text        not null,
  city         text        not null,
  email        text        not null,
  mobile       text        not null,
  nic_path     text,                                    -- storage path of the NIC image
  role         user_role   not null default 'member',
  is_blocked   boolean     not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles (role);
create index if not exists profiles_created_idx on public.profiles (created_at desc);

-- ---------------------------------------------------------------------------
-- fund_types — the options on the member dashboard (data-driven, not hardcoded)
-- ---------------------------------------------------------------------------
create table if not exists public.fund_types (
  id                text primary key,          -- 'monthly' | 'accidental' | 'grocery' | 'electricity'
  name              text    not null,
  description       text,
  gradient          text    not null default 'g-brand',   -- CSS class used by the UI
  icon              text    not null default 'heart',
  document_label    text    not null default 'Supporting document',
  document_required boolean not null default true,
  min_amount        numeric(12,2) not null default 1000,
  max_amount        numeric(12,2),
  is_active         boolean not null default true,
  sort_order        int     not null default 0
);

-- ---------------------------------------------------------------------------
-- fund_requests — an application for help
-- ---------------------------------------------------------------------------
create sequence if not exists public.request_ref_seq start 1001;

create table if not exists public.fund_requests (
  id               uuid primary key default gen_random_uuid(),
  reference        text unique not null
                     default 'SHF-' || to_char(now(), 'YY') || '-' || lpad(nextval('public.request_ref_seq')::text, 5, '0'),
  user_id          uuid not null references public.profiles (id) on delete cascade,
  fund_type_id     text not null references public.fund_types (id),
  amount_requested numeric(12,2) not null check (amount_requested > 0),
  amount_approved  numeric(12,2) check (amount_approved >= 0),
  purpose          text,
  status           request_status not null default 'requested',
  admin_note       text,
  reviewed_by      uuid references public.profiles (id),
  transfer_ref     text,
  transferred_at   timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists fund_requests_user_idx    on public.fund_requests (user_id, created_at desc);
create index if not exists fund_requests_status_idx  on public.fund_requests (status, created_at desc);
create index if not exists fund_requests_type_idx    on public.fund_requests (fund_type_id);

-- ---------------------------------------------------------------------------
-- request_attachments — medical reports, utility bills, receipts…
-- ---------------------------------------------------------------------------
create table if not exists public.request_attachments (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid not null references public.fund_requests (id) on delete cascade,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  path        text not null,                  -- storage object path in the `documents` bucket
  file_name   text not null,
  mime_type   text,
  size_bytes  bigint,
  kind        text not null default 'report', -- report | bill | receipt | other
  created_at  timestamptz not null default now()
);

create index if not exists attachments_request_idx on public.request_attachments (request_id);

-- ---------------------------------------------------------------------------
-- request_events — the audit trail behind the progress tracker
-- ---------------------------------------------------------------------------
create table if not exists public.request_events (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid not null references public.fund_requests (id) on delete cascade,
  status      request_status not null,
  note        text,
  actor_id    uuid references public.profiles (id),
  created_at  timestamptz not null default now()
);

create index if not exists events_request_idx on public.request_events (request_id, created_at);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- security definer so RLS policies can check the role without recursing into
-- the profiles policies themselves.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- A member may edit their own profile, but must never be able to promote
-- themselves to admin or unblock themselves. Enforced here rather than in the
-- RLS WITH CHECK clause, which would have to re-query profiles and recurse.
create or replace function public.guard_profile_privileges()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then
    new.role       := old.role;
    new.is_blocked := old.is_blocked;
  end if;
  return new;
end $$;

drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard before update on public.profiles
  for each row execute function public.guard_profile_privileges();

drop trigger if exists requests_touch on public.fund_requests;
create trigger requests_touch before update on public.fund_requests
  for each row execute function public.touch_updated_at();

-- Every new request opens its timeline at 'requested'.
create or replace function public.log_request_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- note stays null so the app can render it in the member's language
  insert into public.request_events (request_id, status, note, actor_id)
  values (new.id, new.status, null, new.user_id);
  return new;
end $$;

drop trigger if exists requests_log_created on public.fund_requests;
create trigger requests_log_created after insert on public.fund_requests
  for each row execute function public.log_request_created();

-- Every status change appends to the timeline.
create or replace function public.log_request_status_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status is distinct from old.status then
    insert into public.request_events (request_id, status, note, actor_id)
    values (new.id, new.status, new.admin_note, coalesce(new.reviewed_by, auth.uid()));

    if new.status = 'transferred' and new.transferred_at is null then
      new.transferred_at := now();
    end if;
  end if;
  return new;
end $$;

-- BEFORE update so transferred_at can be set on the same row.
drop trigger if exists requests_log_status on public.fund_requests;
create trigger requests_log_status before update on public.fund_requests
  for each row execute function public.log_request_status_change();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
alter table public.profiles            enable row level security;
alter table public.fund_types          enable row level security;
alter table public.fund_requests       enable row level security;
alter table public.request_attachments enable row level security;
alter table public.request_events      enable row level security;

-- profiles ------------------------------------------------------------------
drop policy if exists "profiles read own"    on public.profiles;
drop policy if exists "profiles read admin"  on public.profiles;
drop policy if exists "profiles update own"  on public.profiles;
drop policy if exists "profiles update admin" on public.profiles;
drop policy if exists "profiles insert own"  on public.profiles;

create policy "profiles read own" on public.profiles
  for select using (id = auth.uid());
create policy "profiles read admin" on public.profiles
  for select using (public.is_admin());
create policy "profiles insert own" on public.profiles
  for insert with check (id = auth.uid());
create policy "profiles update own" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());
create policy "profiles update admin" on public.profiles
  for update using (public.is_admin()) with check (public.is_admin());

-- fund_types ----------------------------------------------------------------
drop policy if exists "fund types readable"   on public.fund_types;
drop policy if exists "fund types admin write" on public.fund_types;

create policy "fund types readable" on public.fund_types
  for select using (auth.role() = 'authenticated');
create policy "fund types admin write" on public.fund_types
  for all using (public.is_admin()) with check (public.is_admin());

-- fund_requests -------------------------------------------------------------
drop policy if exists "requests read own"    on public.fund_requests;
drop policy if exists "requests read admin"  on public.fund_requests;
drop policy if exists "requests insert own"  on public.fund_requests;
drop policy if exists "requests update admin" on public.fund_requests;

create policy "requests read own" on public.fund_requests
  for select using (user_id = auth.uid());
create policy "requests read admin" on public.fund_requests
  for select using (public.is_admin());
create policy "requests insert own" on public.fund_requests
  for insert with check (user_id = auth.uid() and status = 'requested');
-- Only admins move a request through the pipeline.
create policy "requests update admin" on public.fund_requests
  for update using (public.is_admin()) with check (public.is_admin());

-- request_attachments -------------------------------------------------------
drop policy if exists "attachments read own"   on public.request_attachments;
drop policy if exists "attachments read admin" on public.request_attachments;
drop policy if exists "attachments insert own" on public.request_attachments;
drop policy if exists "attachments delete own" on public.request_attachments;

create policy "attachments read own" on public.request_attachments
  for select using (user_id = auth.uid());
create policy "attachments read admin" on public.request_attachments
  for select using (public.is_admin());
create policy "attachments insert own" on public.request_attachments
  for insert with check (user_id = auth.uid());
create policy "attachments delete own" on public.request_attachments
  for delete using (user_id = auth.uid());

-- request_events ------------------------------------------------------------
drop policy if exists "events read own"   on public.request_events;
drop policy if exists "events read admin" on public.request_events;
drop policy if exists "events insert admin" on public.request_events;

create policy "events read own" on public.request_events
  for select using (
    exists (select 1 from public.fund_requests r where r.id = request_id and r.user_id = auth.uid())
  );
create policy "events read admin" on public.request_events
  for select using (public.is_admin());
create policy "events insert admin" on public.request_events
  for insert with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Admin dashboard aggregate (runs with the caller's RLS via is_admin check)
-- ---------------------------------------------------------------------------
create or replace function public.admin_stats()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then json_build_object(
    'members',           (select count(*) from public.profiles where role = 'member'),
    'requested',         (select count(*) from public.fund_requests where status = 'requested'),
    'review',            (select count(*) from public.fund_requests where status = 'review'),
    'accepted',          (select count(*) from public.fund_requests where status = 'accepted'),
    'transferred',       (select count(*) from public.fund_requests where status = 'transferred'),
    'rejected',          (select count(*) from public.fund_requests where status = 'rejected'),
    'total_requested',   (select coalesce(sum(amount_requested), 0) from public.fund_requests),
    'total_disbursed',   (select coalesce(sum(coalesce(amount_approved, amount_requested)), 0)
                          from public.fund_requests where status = 'transferred'),
    'by_fund',           (select coalesce(json_agg(t), '[]'::json) from (
                            select ft.id, ft.name, count(r.id) as count,
                                   coalesce(sum(r.amount_requested), 0) as amount
                            from public.fund_types ft
                            left join public.fund_requests r on r.fund_type_id = ft.id
                            group by ft.id, ft.name, ft.sort_order
                            order by ft.sort_order
                          ) t)
  ) else null end;
$$;


-- ####################  migrations/0002_storage.sql  ####################

-- ===========================================================================
-- Storage: one private bucket for every member document
-- (NIC images, medical reports, utility bills, receipts)
--
-- Object paths are always  <user-uuid>/<folder>/<filename>
-- so the first path segment is the owner and policies can key off it.
-- ===========================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'documents',
  'documents',
  false,                                  -- private: served only via signed URLs
  10485760,                               -- 10 MB per file
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'application/pdf']
)
on conflict (id) do update
  set file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types,
      public             = excluded.public;

drop policy if exists "documents insert own"  on storage.objects;
drop policy if exists "documents read own"    on storage.objects;
drop policy if exists "documents read admin"  on storage.objects;
drop policy if exists "documents update own"  on storage.objects;
drop policy if exists "documents delete own"  on storage.objects;
drop policy if exists "documents delete admin" on storage.objects;

-- A member can only write into their own folder.
create policy "documents insert own" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "documents read own" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Admins can read every document — this is what lets them open the medical
-- report or electricity bill attached to a request.
create policy "documents read admin" on storage.objects
  for select to authenticated
  using (bucket_id = 'documents' and public.is_admin());

create policy "documents update own" on storage.objects
  for update to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "documents delete own" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "documents delete admin" on storage.objects
  for delete to authenticated
  using (bucket_id = 'documents' and public.is_admin());


-- ####################  seed.sql  ####################

-- ===========================================================================
-- Seed: the four funds shown on the member dashboard.
-- Safe to re-run — every row is an upsert.
-- ===========================================================================

insert into public.fund_types
  (id, name, description, gradient, icon, document_label, document_required, min_amount, max_amount, sort_order)
values
  ('monthly',     'Monthly Fund',        'Recurring monthly support for registered families',
   'g-brand', 'calendar',  'Income / need proof (optional)',        false, 2000,  50000,  1),

  ('accidental',  'Accidental Fund',     'Emergency help after an accident or medical event',
   'g-rose',  'health',    'Medical report, prescription or hospital bill', true, 5000,  500000, 2),

  ('grocery',     'Grocery Fund',        'Ration and household grocery assistance',
   'g-amber', 'basket',    'Grocery estimate or shop bill',         false, 1000,  30000,  3),

  ('electricity', 'Electricity Bill Fund', 'Help clearing an outstanding electricity bill',
   'g-blue',  'bolt',      'Latest electricity bill',               true,  1000,  80000,  4)
on conflict (id) do update set
  name              = excluded.name,
  description       = excluded.description,
  gradient          = excluded.gradient,
  icon              = excluded.icon,
  document_label    = excluded.document_label,
  document_required = excluded.document_required,
  min_amount        = excluded.min_amount,
  max_amount        = excluded.max_amount,
  sort_order        = excluded.sort_order;

-- ---------------------------------------------------------------------------
-- Promote yourself to admin.
-- 1. Register through the app (or Supabase → Authentication → Add user).
-- 2. Run this with your email:
--
--   update public.profiles set role = 'admin' where email = 'you@example.com';
--
-- Then sign in and open /admin.
-- ---------------------------------------------------------------------------


-- ####################  migrations/0003_urdu.sql  ####################

-- ===========================================================================
-- Bilingual fund copy. The UI strings live in the app; the fund names,
-- descriptions and document labels live here because they are data.
-- ===========================================================================

alter table public.fund_types
  add column if not exists name_ur           text,
  add column if not exists description_ur    text,
  add column if not exists document_label_ur text;

update public.fund_types set
  name_ur           = 'ماہانہ فنڈ',
  description_ur    = 'رجسٹرڈ خاندانوں کے لیے ہر ماہ باقاعدہ امداد',
  document_label_ur = 'آمدنی یا ضرورت کا ثبوت (اختیاری)'
where id = 'monthly';

update public.fund_types set
  name_ur           = 'حادثاتی فنڈ',
  description_ur    = 'حادثے یا طبی ایمرجنسی کے بعد فوری مدد',
  document_label_ur = 'میڈیکل رپورٹ، نسخہ یا ہسپتال کا بل'
where id = 'accidental';

update public.fund_types set
  name_ur           = 'راشن فنڈ',
  description_ur    = 'گھریلو راشن اور اشیائے خوردونوش کی امداد',
  document_label_ur = 'راشن کا تخمینہ یا دکان کا بل'
where id = 'grocery';

update public.fund_types set
  name_ur           = 'بجلی بل فنڈ',
  description_ur    = 'بقایا بجلی کا بل ادا کرنے میں مدد',
  document_label_ur = 'تازہ ترین بجلی کا بل'
where id = 'electricity';


-- ####################  migrations/0004_fix_admin_bootstrap.sql  ####################

-- ===========================================================================
-- Fix: the privilege guard also blocked legitimate admin bootstrapping.
--
-- guard_profile_privileges() reset role/is_blocked whenever is_admin() was
-- false. For a request with no JWT — the SQL Editor, psql, or the service-role
-- key — auth.uid() is null, so is_admin() is false and the guard fired. That
-- made it impossible to create the very first admin.
--
-- The guard only needs to constrain *end users*. Those always carry a JWT, so
-- gate it on auth.uid() being present. The service role is server-only and
-- already bypasses RLS, so this gives it nothing it did not have.
-- ===========================================================================

create or replace function public.guard_profile_privileges()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- Only applies to a signed-in end user. A null auth.uid() means the SQL
  -- Editor or the service-role key, which are trusted by definition.
  if auth.uid() is not null and not public.is_admin() then
    new.role       := old.role;
    new.is_blocked := old.is_blocked;
  end if;
  return new;
end $$;


-- ####################  migrations/0005_stats_counts.sql  ####################

-- ===========================================================================
-- Fix: the dashboard reported "0 registered members" while accounts existed.
--
-- admin_stats() counted only profiles with role = 'member', so any account
-- promoted to admin vanished from the count. A foundation administrator is
-- still a registered account, and staff are a handful of rows — the number
-- people want on the dashboard is "how many accounts exist".
--
-- `members` now counts every profile; `admins` is broken out separately so the
-- split is still visible if it is ever needed.
-- ===========================================================================

create or replace function public.admin_stats()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then json_build_object(
    'members',           (select count(*) from public.profiles),
    'admins',            (select count(*) from public.profiles where role = 'admin'),
    'requested',         (select count(*) from public.fund_requests where status = 'requested'),
    'review',            (select count(*) from public.fund_requests where status = 'review'),
    'accepted',          (select count(*) from public.fund_requests where status = 'accepted'),
    'transferred',       (select count(*) from public.fund_requests where status = 'transferred'),
    'rejected',          (select count(*) from public.fund_requests where status = 'rejected'),
    'total_requested',   (select coalesce(sum(amount_requested), 0) from public.fund_requests),
    'total_disbursed',   (select coalesce(sum(coalesce(amount_approved, amount_requested)), 0)
                          from public.fund_requests where status = 'transferred'),
    'by_fund',           (select coalesce(json_agg(t), '[]'::json) from (
                            select ft.id, ft.name, count(r.id) as count,
                                   coalesce(sum(r.amount_requested), 0) as amount
                            from public.fund_types ft
                            left join public.fund_requests r on r.fund_type_id = ft.id
                            group by ft.id, ft.name, ft.sort_order
                            order by ft.sort_order
                          ) t)
  ) else null end;
$$;


-- ####################  migrations/0006_school_fees_and_budget.sql  ####################

-- ===========================================================================
-- 1. A fifth fund: School Fees
-- 2. Monthly budgets — the foundation sets what it can give in a month, and
--    every transfer draws that balance down.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- School Fees fund
-- ---------------------------------------------------------------------------
insert into public.fund_types
  (id, name, description, gradient, icon, document_label, document_required,
   min_amount, max_amount, sort_order, name_ur, description_ur, document_label_ur)
values
  ('school', 'School Fees Fund',
   'Tuition, admission and exam fees for children in school',
   'g-plum', 'book', 'Fee voucher, challan or school letter', true,
   1000, 120000, 5,
   'تعلیمی فیس فنڈ',
   'بچوں کی ٹیوشن، داخلہ اور امتحانی فیس میں مدد',
   'فیس واؤچر، چالان یا اسکول کا خط')
on conflict (id) do update set
  name              = excluded.name,
  description       = excluded.description,
  gradient          = excluded.gradient,
  icon              = excluded.icon,
  document_label    = excluded.document_label,
  document_required = excluded.document_required,
  min_amount        = excluded.min_amount,
  max_amount        = excluded.max_amount,
  sort_order        = excluded.sort_order,
  name_ur           = excluded.name_ur,
  description_ur    = excluded.description_ur,
  document_label_ur = excluded.document_label_ur;

-- ---------------------------------------------------------------------------
-- Monthly budget
--
-- The remaining balance is never stored — it is always
--   budget − (everything transferred in that month)
-- so it cannot drift out of step with the transfers that caused it.
-- ---------------------------------------------------------------------------
create table if not exists public.monthly_budgets (
  month      date primary key,                       -- always the 1st of the month
  amount     numeric(12,2) not null check (amount >= 0),
  note       text,
  updated_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- guard against a row for the 14th of a month sitting beside one for the 1st
create or replace function public.normalise_budget_month()
returns trigger language plpgsql as $$
begin
  new.month := date_trunc('month', new.month)::date;
  return new;
end $$;

drop trigger if exists budgets_normalise on public.monthly_budgets;
create trigger budgets_normalise before insert or update on public.monthly_budgets
  for each row execute function public.normalise_budget_month();

drop trigger if exists budgets_touch on public.monthly_budgets;
create trigger budgets_touch before update on public.monthly_budgets
  for each row execute function public.touch_updated_at();

alter table public.monthly_budgets enable row level security;

drop policy if exists "budgets admin read"  on public.monthly_budgets;
drop policy if exists "budgets admin write" on public.monthly_budgets;

-- Budgets are internal finance: administrators only, members never see them.
create policy "budgets admin read" on public.monthly_budgets
  for select using (public.is_admin());
create policy "budgets admin write" on public.monthly_budgets
  for all using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Budget position for a given month
-- ---------------------------------------------------------------------------
create or replace function public.budget_status(p_month date default current_date)
returns json
language sql
stable
security definer
set search_path = public
as $$
  with m as (
    select date_trunc('month', p_month)::date as start_day,
           (date_trunc('month', p_month) + interval '1 month')::date as end_day
  ),
  spent as (
    select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) as total,
           count(*) as transfers
    from public.fund_requests r, m
    where r.status = 'transferred'
      and r.transferred_at >= m.start_day
      and r.transferred_at <  m.end_day
  ),
  committed as (
    -- approved but not yet paid: money the foundation has promised this month
    select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) as total
    from public.fund_requests r
    where r.status = 'accepted'
  )
  select case when public.is_admin() then json_build_object(
    'month',      (select start_day from m),
    'budget',     coalesce((select b.amount from public.monthly_budgets b, m where b.month = m.start_day), 0),
    'spent',      (select total from spent),
    'transfers',  (select transfers from spent),
    'committed',  (select total from committed),
    'remaining',  coalesce((select b.amount from public.monthly_budgets b, m where b.month = m.start_day), 0)
                    - (select total from spent),
    'has_budget', exists (select 1 from public.monthly_budgets b, m where b.month = m.start_day)
  ) else null end;
$$;

-- ---------------------------------------------------------------------------
-- Recent months, for the budget history table
-- ---------------------------------------------------------------------------
create or replace function public.budget_history(p_months int default 12)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then coalesce((
    select json_agg(t order by t.month desc) from (
      select
        g.month::date as month,
        coalesce(b.amount, 0) as budget,
        coalesce((
          select sum(coalesce(r.amount_approved, r.amount_requested))
          from public.fund_requests r
          where r.status = 'transferred'
            and r.transferred_at >= g.month
            and r.transferred_at <  g.month + interval '1 month'
        ), 0) as spent
      from generate_series(
             date_trunc('month', current_date) - ((greatest(p_months, 1) - 1) || ' months')::interval,
             date_trunc('month', current_date),
             interval '1 month'
           ) as g(month)
      left join public.monthly_budgets b on b.month = g.month::date
    ) t
  ), '[]'::json) else null end;
$$;
