-- =====================================================================
-- Subaidar Hasnain Foundation — COMPLETE SETUP
--
-- Paste this whole file into Supabase → SQL Editor → Run.
-- It is idempotent: safe to run again after a change.
--
-- Combines, in order:
--   migrations/0001_init.sql
--   migrations/0002_storage.sql
--   seed.sql
--   migrations/0003_urdu.sql
--   migrations/0004_fix_admin_bootstrap.sql
--   migrations/0005_stats_counts.sql
--   migrations/0006_school_fees_and_budget.sql
--   migrations/0007_bank_details.sql
--   migrations/0008_transfer_receipts.sql
--   migrations/0009_recurring_monthly.sql
--   migrations/0010_donors.sql
--   migrations/0011_family_details.sql
--   migrations/0012_donors_are_members.sql
--   migrations/0013_transfer_within_fund.sql
--   migrations/0014_payment_method.sql
-- Generated by supabase/build-setup.mjs — edit the source files, not this one.
-- =====================================================================



-- ####################  migrations/0001_init.sql  ####################

-- ===========================================================================
-- Subaidar Hasnain Foundation — core schema
-- Run in Supabase → SQL Editor (or `supabase db push`).
-- ===========================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin
  create type gender_t as enum ('male', 'female', 'other');
exception when duplicate_object then null; end $$;

do $$ begin
  -- The four stages the member sees, plus a terminal 'rejected'.
  create type request_status as enum ('requested', 'review', 'accepted', 'transferred', 'rejected');
exception when duplicate_object then null; end $$;

do $$ begin
  create type user_role as enum ('member', 'admin');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- profiles — one row per auth user, holds the registration details
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  full_name    text        not null,
  gender       gender_t    not null,
  age          int         not null check (age between 12 and 120),
  country      text        not null,
  city         text        not null,
  email        text        not null,
  mobile       text        not null,
  nic_path     text,                                    -- storage path of the NIC image
  role         user_role   not null default 'member',
  is_blocked   boolean     not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles (role);
create index if not exists profiles_created_idx on public.profiles (created_at desc);

-- ---------------------------------------------------------------------------
-- fund_types — the options on the member dashboard (data-driven, not hardcoded)
-- ---------------------------------------------------------------------------
create table if not exists public.fund_types (
  id                text primary key,          -- 'monthly' | 'accidental' | 'grocery' | 'electricity'
  name              text    not null,
  description       text,
  gradient          text    not null default 'g-brand',   -- CSS class used by the UI
  icon              text    not null default 'heart',
  document_label    text    not null default 'Supporting document',
  document_required boolean not null default true,
  min_amount        numeric(12,2) not null default 1000,
  max_amount        numeric(12,2),
  is_active         boolean not null default true,
  sort_order        int     not null default 0
);

-- ---------------------------------------------------------------------------
-- fund_requests — an application for help
-- ---------------------------------------------------------------------------
create sequence if not exists public.request_ref_seq start 1001;

create table if not exists public.fund_requests (
  id               uuid primary key default gen_random_uuid(),
  reference        text unique not null
                     default 'SHF-' || to_char(now(), 'YY') || '-' || lpad(nextval('public.request_ref_seq')::text, 5, '0'),
  user_id          uuid not null references public.profiles (id) on delete cascade,
  fund_type_id     text not null references public.fund_types (id),
  amount_requested numeric(12,2) not null check (amount_requested > 0),
  amount_approved  numeric(12,2) check (amount_approved >= 0),
  purpose          text,
  status           request_status not null default 'requested',
  admin_note       text,
  reviewed_by      uuid references public.profiles (id),
  transfer_ref     text,
  transferred_at   timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists fund_requests_user_idx    on public.fund_requests (user_id, created_at desc);
create index if not exists fund_requests_status_idx  on public.fund_requests (status, created_at desc);
create index if not exists fund_requests_type_idx    on public.fund_requests (fund_type_id);

-- ---------------------------------------------------------------------------
-- request_attachments — medical reports, utility bills, receipts…
-- ---------------------------------------------------------------------------
create table if not exists public.request_attachments (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid not null references public.fund_requests (id) on delete cascade,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  path        text not null,                  -- storage object path in the `documents` bucket
  file_name   text not null,
  mime_type   text,
  size_bytes  bigint,
  kind        text not null default 'report', -- report | bill | receipt | other
  created_at  timestamptz not null default now()
);

create index if not exists attachments_request_idx on public.request_attachments (request_id);

-- ---------------------------------------------------------------------------
-- request_events — the audit trail behind the progress tracker
-- ---------------------------------------------------------------------------
create table if not exists public.request_events (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid not null references public.fund_requests (id) on delete cascade,
  status      request_status not null,
  note        text,
  actor_id    uuid references public.profiles (id),
  created_at  timestamptz not null default now()
);

create index if not exists events_request_idx on public.request_events (request_id, created_at);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- security definer so RLS policies can check the role without recursing into
-- the profiles policies themselves.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- A member may edit their own profile, but must never be able to promote
-- themselves to admin or unblock themselves. Enforced here rather than in the
-- RLS WITH CHECK clause, which would have to re-query profiles and recurse.
create or replace function public.guard_profile_privileges()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then
    new.role       := old.role;
    new.is_blocked := old.is_blocked;
  end if;
  return new;
end $$;

drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard before update on public.profiles
  for each row execute function public.guard_profile_privileges();

drop trigger if exists requests_touch on public.fund_requests;
create trigger requests_touch before update on public.fund_requests
  for each row execute function public.touch_updated_at();

-- Every new request opens its timeline at 'requested'.
create or replace function public.log_request_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- note stays null so the app can render it in the member's language
  insert into public.request_events (request_id, status, note, actor_id)
  values (new.id, new.status, null, new.user_id);
  return new;
end $$;

drop trigger if exists requests_log_created on public.fund_requests;
create trigger requests_log_created after insert on public.fund_requests
  for each row execute function public.log_request_created();

-- Every status change appends to the timeline.
create or replace function public.log_request_status_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status is distinct from old.status then
    insert into public.request_events (request_id, status, note, actor_id)
    values (new.id, new.status, new.admin_note, coalesce(new.reviewed_by, auth.uid()));

    if new.status = 'transferred' and new.transferred_at is null then
      new.transferred_at := now();
    end if;
  end if;
  return new;
end $$;

-- BEFORE update so transferred_at can be set on the same row.
drop trigger if exists requests_log_status on public.fund_requests;
create trigger requests_log_status before update on public.fund_requests
  for each row execute function public.log_request_status_change();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
alter table public.profiles            enable row level security;
alter table public.fund_types          enable row level security;
alter table public.fund_requests       enable row level security;
alter table public.request_attachments enable row level security;
alter table public.request_events      enable row level security;

-- profiles ------------------------------------------------------------------
drop policy if exists "profiles read own"    on public.profiles;
drop policy if exists "profiles read admin"  on public.profiles;
drop policy if exists "profiles update own"  on public.profiles;
drop policy if exists "profiles update admin" on public.profiles;
drop policy if exists "profiles insert own"  on public.profiles;

create policy "profiles read own" on public.profiles
  for select using (id = auth.uid());
create policy "profiles read admin" on public.profiles
  for select using (public.is_admin());
create policy "profiles insert own" on public.profiles
  for insert with check (id = auth.uid());
create policy "profiles update own" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());
create policy "profiles update admin" on public.profiles
  for update using (public.is_admin()) with check (public.is_admin());

-- fund_types ----------------------------------------------------------------
drop policy if exists "fund types readable"   on public.fund_types;
drop policy if exists "fund types admin write" on public.fund_types;

create policy "fund types readable" on public.fund_types
  for select using (auth.role() = 'authenticated');
create policy "fund types admin write" on public.fund_types
  for all using (public.is_admin()) with check (public.is_admin());

-- fund_requests -------------------------------------------------------------
drop policy if exists "requests read own"    on public.fund_requests;
drop policy if exists "requests read admin"  on public.fund_requests;
drop policy if exists "requests insert own"  on public.fund_requests;
drop policy if exists "requests update admin" on public.fund_requests;

create policy "requests read own" on public.fund_requests
  for select using (user_id = auth.uid());
create policy "requests read admin" on public.fund_requests
  for select using (public.is_admin());
create policy "requests insert own" on public.fund_requests
  for insert with check (user_id = auth.uid() and status = 'requested');
-- Only admins move a request through the pipeline.
create policy "requests update admin" on public.fund_requests
  for update using (public.is_admin()) with check (public.is_admin());

-- request_attachments -------------------------------------------------------
drop policy if exists "attachments read own"   on public.request_attachments;
drop policy if exists "attachments read admin" on public.request_attachments;
drop policy if exists "attachments insert own" on public.request_attachments;
drop policy if exists "attachments delete own" on public.request_attachments;

create policy "attachments read own" on public.request_attachments
  for select using (user_id = auth.uid());
create policy "attachments read admin" on public.request_attachments
  for select using (public.is_admin());
create policy "attachments insert own" on public.request_attachments
  for insert with check (user_id = auth.uid());
create policy "attachments delete own" on public.request_attachments
  for delete using (user_id = auth.uid());

-- request_events ------------------------------------------------------------
drop policy if exists "events read own"   on public.request_events;
drop policy if exists "events read admin" on public.request_events;
drop policy if exists "events insert admin" on public.request_events;

create policy "events read own" on public.request_events
  for select using (
    exists (select 1 from public.fund_requests r where r.id = request_id and r.user_id = auth.uid())
  );
create policy "events read admin" on public.request_events
  for select using (public.is_admin());
create policy "events insert admin" on public.request_events
  for insert with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Admin dashboard aggregate (runs with the caller's RLS via is_admin check)
-- ---------------------------------------------------------------------------
create or replace function public.admin_stats()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then json_build_object(
    'members',           (select count(*) from public.profiles where role = 'member'),
    'requested',         (select count(*) from public.fund_requests where status = 'requested'),
    'review',            (select count(*) from public.fund_requests where status = 'review'),
    'accepted',          (select count(*) from public.fund_requests where status = 'accepted'),
    'transferred',       (select count(*) from public.fund_requests where status = 'transferred'),
    'rejected',          (select count(*) from public.fund_requests where status = 'rejected'),
    'total_requested',   (select coalesce(sum(amount_requested), 0) from public.fund_requests),
    'total_disbursed',   (select coalesce(sum(coalesce(amount_approved, amount_requested)), 0)
                          from public.fund_requests where status = 'transferred'),
    'by_fund',           (select coalesce(json_agg(t), '[]'::json) from (
                            select ft.id, ft.name, count(r.id) as count,
                                   coalesce(sum(r.amount_requested), 0) as amount
                            from public.fund_types ft
                            left join public.fund_requests r on r.fund_type_id = ft.id
                            group by ft.id, ft.name, ft.sort_order
                            order by ft.sort_order
                          ) t)
  ) else null end;
$$;


-- ####################  migrations/0002_storage.sql  ####################

-- ===========================================================================
-- Storage: one private bucket for every member document
-- (NIC images, medical reports, utility bills, receipts)
--
-- Object paths are always  <user-uuid>/<folder>/<filename>
-- so the first path segment is the owner and policies can key off it.
-- ===========================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'documents',
  'documents',
  false,                                  -- private: served only via signed URLs
  10485760,                               -- 10 MB per file
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'application/pdf']
)
on conflict (id) do update
  set file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types,
      public             = excluded.public;

drop policy if exists "documents insert own"  on storage.objects;
drop policy if exists "documents read own"    on storage.objects;
drop policy if exists "documents read admin"  on storage.objects;
drop policy if exists "documents update own"  on storage.objects;
drop policy if exists "documents delete own"  on storage.objects;
drop policy if exists "documents delete admin" on storage.objects;

-- A member can only write into their own folder.
create policy "documents insert own" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "documents read own" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Admins can read every document — this is what lets them open the medical
-- report or electricity bill attached to a request.
create policy "documents read admin" on storage.objects
  for select to authenticated
  using (bucket_id = 'documents' and public.is_admin());

create policy "documents update own" on storage.objects
  for update to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "documents delete own" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "documents delete admin" on storage.objects
  for delete to authenticated
  using (bucket_id = 'documents' and public.is_admin());


-- ####################  seed.sql  ####################

-- ===========================================================================
-- Seed: the four funds shown on the member dashboard.
-- Safe to re-run — every row is an upsert.
-- ===========================================================================

insert into public.fund_types
  (id, name, description, gradient, icon, document_label, document_required, min_amount, max_amount, sort_order)
values
  ('monthly',     'Monthly Fund',        'Recurring monthly support for registered families',
   'g-brand', 'calendar',  'Income / need proof (optional)',        false, 2000,  50000,  1),

  ('accidental',  'Accidental Fund',     'Emergency help after an accident or medical event',
   'g-rose',  'health',    'Medical report, prescription or hospital bill', true, 5000,  500000, 2),

  ('grocery',     'Grocery Fund',        'Ration and household grocery assistance',
   'g-amber', 'basket',    'Grocery estimate or shop bill',         false, 1000,  30000,  3),

  ('electricity', 'Electricity Bill Fund', 'Help clearing an outstanding electricity bill',
   'g-blue',  'bolt',      'Latest electricity bill',               true,  1000,  80000,  4)
on conflict (id) do update set
  name              = excluded.name,
  description       = excluded.description,
  gradient          = excluded.gradient,
  icon              = excluded.icon,
  document_label    = excluded.document_label,
  document_required = excluded.document_required,
  min_amount        = excluded.min_amount,
  max_amount        = excluded.max_amount,
  sort_order        = excluded.sort_order;

-- ---------------------------------------------------------------------------
-- Promote yourself to admin.
-- 1. Register through the app (or Supabase → Authentication → Add user).
-- 2. Run this with your email:
--
--   update public.profiles set role = 'admin' where email = 'you@example.com';
--
-- Then sign in and open /admin.
-- ---------------------------------------------------------------------------


-- ####################  migrations/0003_urdu.sql  ####################

-- ===========================================================================
-- Bilingual fund copy. The UI strings live in the app; the fund names,
-- descriptions and document labels live here because they are data.
-- ===========================================================================

alter table public.fund_types
  add column if not exists name_ur           text,
  add column if not exists description_ur    text,
  add column if not exists document_label_ur text;

update public.fund_types set
  name_ur           = 'ماہانہ فنڈ',
  description_ur    = 'رجسٹرڈ خاندانوں کے لیے ہر ماہ باقاعدہ امداد',
  document_label_ur = 'آمدنی یا ضرورت کا ثبوت (اختیاری)'
where id = 'monthly';

update public.fund_types set
  name_ur           = 'حادثاتی فنڈ',
  description_ur    = 'حادثے یا طبی ایمرجنسی کے بعد فوری مدد',
  document_label_ur = 'میڈیکل رپورٹ، نسخہ یا ہسپتال کا بل'
where id = 'accidental';

update public.fund_types set
  name_ur           = 'راشن فنڈ',
  description_ur    = 'گھریلو راشن اور اشیائے خوردونوش کی امداد',
  document_label_ur = 'راشن کا تخمینہ یا دکان کا بل'
where id = 'grocery';

update public.fund_types set
  name_ur           = 'بجلی بل فنڈ',
  description_ur    = 'بقایا بجلی کا بل ادا کرنے میں مدد',
  document_label_ur = 'تازہ ترین بجلی کا بل'
where id = 'electricity';


-- ####################  migrations/0004_fix_admin_bootstrap.sql  ####################

-- ===========================================================================
-- Fix: the privilege guard also blocked legitimate admin bootstrapping.
--
-- guard_profile_privileges() reset role/is_blocked whenever is_admin() was
-- false. For a request with no JWT — the SQL Editor, psql, or the service-role
-- key — auth.uid() is null, so is_admin() is false and the guard fired. That
-- made it impossible to create the very first admin.
--
-- The guard only needs to constrain *end users*. Those always carry a JWT, so
-- gate it on auth.uid() being present. The service role is server-only and
-- already bypasses RLS, so this gives it nothing it did not have.
-- ===========================================================================

create or replace function public.guard_profile_privileges()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- Only applies to a signed-in end user. A null auth.uid() means the SQL
  -- Editor or the service-role key, which are trusted by definition.
  if auth.uid() is not null and not public.is_admin() then
    new.role       := old.role;
    new.is_blocked := old.is_blocked;
  end if;
  return new;
end $$;


-- ####################  migrations/0005_stats_counts.sql  ####################

-- ===========================================================================
-- Fix: the dashboard reported "0 registered members" while accounts existed.
--
-- admin_stats() counted only profiles with role = 'member', so any account
-- promoted to admin vanished from the count. A foundation administrator is
-- still a registered account, and staff are a handful of rows — the number
-- people want on the dashboard is "how many accounts exist".
--
-- `members` now counts every profile; `admins` is broken out separately so the
-- split is still visible if it is ever needed.
-- ===========================================================================

create or replace function public.admin_stats()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then json_build_object(
    'members',           (select count(*) from public.profiles),
    'admins',            (select count(*) from public.profiles where role = 'admin'),
    'requested',         (select count(*) from public.fund_requests where status = 'requested'),
    'review',            (select count(*) from public.fund_requests where status = 'review'),
    'accepted',          (select count(*) from public.fund_requests where status = 'accepted'),
    'transferred',       (select count(*) from public.fund_requests where status = 'transferred'),
    'rejected',          (select count(*) from public.fund_requests where status = 'rejected'),
    'total_requested',   (select coalesce(sum(amount_requested), 0) from public.fund_requests),
    'total_disbursed',   (select coalesce(sum(coalesce(amount_approved, amount_requested)), 0)
                          from public.fund_requests where status = 'transferred'),
    'by_fund',           (select coalesce(json_agg(t), '[]'::json) from (
                            select ft.id, ft.name, count(r.id) as count,
                                   coalesce(sum(r.amount_requested), 0) as amount
                            from public.fund_types ft
                            left join public.fund_requests r on r.fund_type_id = ft.id
                            group by ft.id, ft.name, ft.sort_order
                            order by ft.sort_order
                          ) t)
  ) else null end;
$$;


-- ####################  migrations/0006_school_fees_and_budget.sql  ####################

-- ===========================================================================
-- 1. A fifth fund: School Fees
-- 2. Monthly budgets — the foundation sets what it can give in a month, and
--    every transfer draws that balance down.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- School Fees fund
-- ---------------------------------------------------------------------------
insert into public.fund_types
  (id, name, description, gradient, icon, document_label, document_required,
   min_amount, max_amount, sort_order, name_ur, description_ur, document_label_ur)
values
  ('school', 'School Fees Fund',
   'Tuition, admission and exam fees for children in school',
   'g-plum', 'book', 'Fee voucher, challan or school letter', true,
   1000, 120000, 5,
   'تعلیمی فیس فنڈ',
   'بچوں کی ٹیوشن، داخلہ اور امتحانی فیس میں مدد',
   'فیس واؤچر، چالان یا اسکول کا خط')
on conflict (id) do update set
  name              = excluded.name,
  description       = excluded.description,
  gradient          = excluded.gradient,
  icon              = excluded.icon,
  document_label    = excluded.document_label,
  document_required = excluded.document_required,
  min_amount        = excluded.min_amount,
  max_amount        = excluded.max_amount,
  sort_order        = excluded.sort_order,
  name_ur           = excluded.name_ur,
  description_ur    = excluded.description_ur,
  document_label_ur = excluded.document_label_ur;

-- ---------------------------------------------------------------------------
-- Monthly budget
--
-- The remaining balance is never stored — it is always
--   budget − (everything transferred in that month)
-- so it cannot drift out of step with the transfers that caused it.
-- ---------------------------------------------------------------------------
create table if not exists public.monthly_budgets (
  month      date primary key,                       -- always the 1st of the month
  amount     numeric(12,2) not null check (amount >= 0),
  note       text,
  updated_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- guard against a row for the 14th of a month sitting beside one for the 1st
create or replace function public.normalise_budget_month()
returns trigger language plpgsql as $$
begin
  new.month := date_trunc('month', new.month)::date;
  return new;
end $$;

drop trigger if exists budgets_normalise on public.monthly_budgets;
create trigger budgets_normalise before insert or update on public.monthly_budgets
  for each row execute function public.normalise_budget_month();

drop trigger if exists budgets_touch on public.monthly_budgets;
create trigger budgets_touch before update on public.monthly_budgets
  for each row execute function public.touch_updated_at();

alter table public.monthly_budgets enable row level security;

drop policy if exists "budgets admin read"  on public.monthly_budgets;
drop policy if exists "budgets admin write" on public.monthly_budgets;

-- Budgets are internal finance: administrators only, members never see them.
create policy "budgets admin read" on public.monthly_budgets
  for select using (public.is_admin());
create policy "budgets admin write" on public.monthly_budgets
  for all using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Budget position for a given month
-- ---------------------------------------------------------------------------
create or replace function public.budget_status(p_month date default current_date)
returns json
language sql
stable
security definer
set search_path = public
as $$
  with m as (
    select date_trunc('month', p_month)::date as start_day,
           (date_trunc('month', p_month) + interval '1 month')::date as end_day
  ),
  spent as (
    select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) as total,
           count(*) as transfers
    from public.fund_requests r, m
    where r.status = 'transferred'
      and r.transferred_at >= m.start_day
      and r.transferred_at <  m.end_day
  ),
  committed as (
    -- approved but not yet paid: money the foundation has promised this month
    select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) as total
    from public.fund_requests r
    where r.status = 'accepted'
  )
  select case when public.is_admin() then json_build_object(
    'month',      (select start_day from m),
    'budget',     coalesce((select b.amount from public.monthly_budgets b, m where b.month = m.start_day), 0),
    'spent',      (select total from spent),
    'transfers',  (select transfers from spent),
    'committed',  (select total from committed),
    'remaining',  coalesce((select b.amount from public.monthly_budgets b, m where b.month = m.start_day), 0)
                    - (select total from spent),
    'has_budget', exists (select 1 from public.monthly_budgets b, m where b.month = m.start_day)
  ) else null end;
$$;

-- ---------------------------------------------------------------------------
-- Recent months, for the budget history table
-- ---------------------------------------------------------------------------
create or replace function public.budget_history(p_months int default 12)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then coalesce((
    select json_agg(t order by t.month desc) from (
      select
        g.month::date as month,
        coalesce(b.amount, 0) as budget,
        coalesce((
          select sum(coalesce(r.amount_approved, r.amount_requested))
          from public.fund_requests r
          where r.status = 'transferred'
            and r.transferred_at >= g.month
            and r.transferred_at <  g.month + interval '1 month'
        ), 0) as spent
      from generate_series(
             date_trunc('month', current_date) - ((greatest(p_months, 1) - 1) || ' months')::interval,
             date_trunc('month', current_date),
             interval '1 month'
           ) as g(month)
      left join public.monthly_budgets b on b.month = g.month::date
    ) t
  ), '[]'::json) else null end;
$$;


-- ####################  migrations/0007_bank_details.sql  ####################

-- ===========================================================================
-- Bank details on the profile.
--
-- The foundation transfers money; it needs somewhere to send it. Until now
-- that destination was collected off-system, which meant an approved
-- application could sit waiting on a phone call. These three columns make the
-- destination part of the member's record, and a trigger refuses to accept a
-- new application from a member who has not supplied one.
-- ===========================================================================

alter table public.profiles
  add column if not exists bank_name           text,
  add column if not exists bank_account_title  text,
  add column if not exists bank_account_number text;

comment on column public.profiles.bank_name is
  'Bank / microfinance bank / wallet, chosen from the list in src/lib/banks.ts.';
comment on column public.profiles.bank_account_title is
  'Account holder name, as printed on the account.';
comment on column public.profiles.bank_account_number is
  'IBAN (PK…, 24 chars) or plain account number. Stored uppercase, no spaces.';

-- Length floors only. The exact shape differs between an IBAN, a 14-digit
-- account number and an 11-digit wallet, so the app validates the shape and
-- the database refuses only what is obviously unusable.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_bank_account_number_len') then
    alter table public.profiles
      add constraint profiles_bank_account_number_len
      check (bank_account_number is null or char_length(bank_account_number) between 6 and 34);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'profiles_bank_account_title_len') then
    alter table public.profiles
      add constraint profiles_bank_account_title_len
      check (bank_account_title is null or char_length(btrim(bank_account_title)) >= 3);
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- A member cannot apply without a payout destination.
--
-- This lives in Postgres rather than only in /api/requests so that the rule
-- holds for anything that talks to the database — the native app, a future
-- import script, or an admin acting on a member's behalf.
-- ---------------------------------------------------------------------------
create or replace function public.require_bank_details()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  p record;
begin
  select bank_name, bank_account_title, bank_account_number
    into p
    from public.profiles
   where id = new.user_id;

  -- `found`, not `p is null`: a real profile whose bank columns are all empty
  -- also yields an all-NULL record, and that is a different error entirely.
  if not found then
    raise exception 'No profile found for this account.'
      using errcode = 'check_violation';
  end if;

  if coalesce(btrim(p.bank_name), '') = ''
     or coalesce(btrim(p.bank_account_title), '') = ''
     or coalesce(btrim(p.bank_account_number), '') = '' then
    raise exception 'Add your bank details before applying for a fund.'
      using errcode = 'check_violation';
  end if;

  return new;
end $$;

drop trigger if exists trg_require_bank_details on public.fund_requests;
create trigger trg_require_bank_details
  before insert on public.fund_requests
  for each row execute function public.require_bank_details();


-- ####################  migrations/0008_transfer_receipts.sql  ####################

-- ===========================================================================
-- Transfer receipts.
--
-- When an admin marks an application transferred they can attach the bank or
-- wallet receipt. The receipt is filed into the *member's* case file — stored
-- under their folder, recorded against their user_id — because it is evidence
-- for them, not for us: proof the money was sent, visible on their own
-- application screen without any new read policy.
--
-- That leaves only the write side to open up.
-- ===========================================================================

-- Storage: an admin may write into any member's folder. They can already read
-- and delete every object in the bucket, so this closes the last gap rather
-- than opening a new kind of access.
drop policy if exists "documents insert admin" on storage.objects;
create policy "documents insert admin" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'documents' and public.is_admin());

-- Attachments: an admin may record a file against any request. The row still
-- carries the member's user_id, which is what makes "attachments read own"
-- show it to them.
drop policy if exists "attachments insert admin" on public.request_attachments;
create policy "attachments insert admin" on public.request_attachments
  for insert with check (public.is_admin());

-- Filing the wrong receipt against a case should be fixable.
drop policy if exists "attachments delete admin" on public.request_attachments;
create policy "attachments delete admin" on public.request_attachments
  for delete using (public.is_admin());

-- The kind column has always been free text with 'report' as the default.
-- Name the values now that a second writer is using it.
comment on column public.request_attachments.kind is
  'report | bill | cnic | receipt | other — receipt is written by an admin on transfer.';

create index if not exists attachments_kind_idx
  on public.request_attachments (request_id, kind);


-- ####################  migrations/0009_recurring_monthly.sql  ####################

-- ===========================================================================
-- Standing monthly support.
--
-- The Monthly Fund is recurring by nature: a family approved for it in March
-- needs it again in April. Until now someone had to remember to re-apply, and
-- the ones least likely to remember are the ones who need it most.
--
-- Approving a monthly application now enrols the member, and on the 1st of
-- each month the system files the next application on their behalf. It arrives
-- as a normal application at `requested` — the committee still decides every
-- month, and every decision is still on the record.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Which funds recur is data, like everything else about a fund.
-- ---------------------------------------------------------------------------
alter table public.fund_types
  add column if not exists is_recurring boolean not null default false;

comment on column public.fund_types.is_recurring is
  'Approving one of these enrols the member for an automatic application each month.';

update public.fund_types set is_recurring = true where id = 'monthly';

-- A flag rather than a sentence in `purpose`: both portals need to label these
-- rows, and they label them in different languages.
alter table public.fund_requests
  add column if not exists is_automatic boolean not null default false;

comment on column public.fund_requests.is_automatic is
  'Filed by generate_recurring_requests() rather than by the member.';

-- ---------------------------------------------------------------------------
-- The standing arrangement itself.
-- ---------------------------------------------------------------------------
create table if not exists public.recurring_grants (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references public.profiles (id) on delete cascade,
  fund_type_id      text not null references public.fund_types (id),
  amount            numeric(12,2) not null check (amount > 0),
  source_request_id uuid references public.fund_requests (id) on delete set null,
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  last_generated_on date,               -- the month we last filed for, as its 1st
  -- One arrangement per member per fund: approving next month's application
  -- must not enrol them twice.
  unique (user_id, fund_type_id)
);

create index if not exists recurring_active_idx
  on public.recurring_grants (is_active, fund_type_id);

alter table public.recurring_grants enable row level security;

drop policy if exists "recurring read own"   on public.recurring_grants;
drop policy if exists "recurring read admin" on public.recurring_grants;
drop policy if exists "recurring write admin" on public.recurring_grants;

-- A member can see that they are enrolled; only staff can change it.
create policy "recurring read own" on public.recurring_grants
  for select using (user_id = auth.uid());
create policy "recurring read admin" on public.recurring_grants
  for select using (public.is_admin());
create policy "recurring write admin" on public.recurring_grants
  for all using (public.is_admin()) with check (public.is_admin());

drop trigger if exists trg_recurring_touch on public.recurring_grants;
create trigger trg_recurring_touch
  before update on public.recurring_grants
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Approving a recurring fund enrols the member.
--
-- Fires only on the move *into* accepted, so re-saving a note on an already
-- approved application does not reset the arrangement. The amount tracks the
-- most recent approval: if the committee approves a different figure, that is
-- the figure that recurs.
-- ---------------------------------------------------------------------------
create or replace function public.enrol_recurring_grant()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recurring boolean;
begin
  if new.status <> 'accepted' or old.status = 'accepted' then
    return new;
  end if;

  select is_recurring into recurring from public.fund_types where id = new.fund_type_id;
  if not coalesce(recurring, false) then
    return new;
  end if;

  insert into public.recurring_grants (user_id, fund_type_id, amount, source_request_id,
                                       last_generated_on)
  values (new.user_id, new.fund_type_id,
          coalesce(new.amount_approved, new.amount_requested), new.id,
          date_trunc('month', (now() at time zone 'Asia/Karachi'))::date)
  on conflict (user_id, fund_type_id) do update set
    amount            = excluded.amount,
    source_request_id = excluded.source_request_id,
    is_active         = true;

  return new;
end $$;

drop trigger if exists trg_enrol_recurring on public.fund_requests;
create trigger trg_enrol_recurring
  after update of status on public.fund_requests
  for each row execute function public.enrol_recurring_grant();

-- ---------------------------------------------------------------------------
-- File this month's applications.
--
-- Idempotent on purpose. It is safe to run every day, twice, or by hand: an
-- arrangement that already has an application this month is skipped, so a
-- missed night is caught up the next day rather than lost, and a double-run
-- cannot double-apply.
--
-- Months are Pakistan months. "The 1st" for a foundation in Rawalpindi is not
-- midnight UTC, which is five in the morning there.
-- ---------------------------------------------------------------------------
create or replace function public.generate_recurring_requests()
returns table (created int, skipped int)
language plpgsql
security definer
set search_path = public
as $$
declare
  g            record;
  this_month   date := date_trunc('month', (now() at time zone 'Asia/Karachi'))::date;
  next_month   date := (this_month + interval '1 month')::date;
  n_created    int  := 0;
  n_skipped    int  := 0;
begin
  for g in
    select r.*, p.is_blocked, p.bank_name, p.bank_account_title, p.bank_account_number
      from public.recurring_grants r
      join public.profiles p on p.id = r.user_id
     where r.is_active
  loop
    -- A blocked member, or one whose payout account has been cleared, is
    -- skipped rather than failed: one bad row must not stop the whole month.
    if g.is_blocked
       or coalesce(btrim(g.bank_name), '') = ''
       or coalesce(btrim(g.bank_account_title), '') = ''
       or coalesce(btrim(g.bank_account_number), '') = '' then
      n_skipped := n_skipped + 1;
      continue;
    end if;

    if exists (
      select 1 from public.fund_requests q
       where q.user_id = g.user_id
         and q.fund_type_id = g.fund_type_id
         and (q.created_at at time zone 'Asia/Karachi') >= this_month
         and (q.created_at at time zone 'Asia/Karachi') <  next_month
    ) then
      n_skipped := n_skipped + 1;
      continue;
    end if;

    insert into public.fund_requests (user_id, fund_type_id, amount_requested, status, is_automatic)
    values (g.user_id, g.fund_type_id, g.amount, 'requested', true);

    update public.recurring_grants
       set last_generated_on = this_month
     where id = g.id;

    n_created := n_created + 1;
  end loop;

  return query select n_created, n_skipped;
end $$;

revoke all on function public.generate_recurring_requests() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Run it nightly, if this project has pg_cron.
--
-- 19:05 UTC is 00:05 in Karachi, so the job's first run of a month lands just
-- after midnight on the 1st. Wrapped because pg_cron is not enabled on every
-- Supabase plan — without it the same function is called by /api/cron/monthly,
-- and because the function is idempotent it does not matter if both run.
-- ---------------------------------------------------------------------------
do $$
begin
  create extension if not exists pg_cron;

  perform cron.unschedule('shf-monthly-grants')
    where exists (select 1 from cron.job where jobname = 'shf-monthly-grants');

  perform cron.schedule(
    'shf-monthly-grants',
    '5 19 * * *',
    $job$ select public.generate_recurring_requests(); $job$
  );
exception when others then
  raise notice 'pg_cron unavailable (%), falling back to /api/cron/monthly', sqlerrm;
end $$;


-- ####################  migrations/0010_donors.sql  ####################

-- ===========================================================================
-- Donors.
--
-- The budget was a number somebody typed in. Where it came from lived outside
-- the system, which meant the month's capacity and the month's giving were two
-- separate truths. Donors are people who give each month; their donations for a
-- month add to that month's fund, so the figure the committee spends against is
-- the money that actually arrived.
--
-- A month's fund is therefore  set budget + donations received that month.
-- The set budget stays: some months carry a reserve, or a single large gift
-- that is not a standing donor.
-- ===========================================================================

create table if not exists public.donors (
  id             uuid primary key default gen_random_uuid(),
  name           text not null check (char_length(btrim(name)) >= 2),
  contact        text,                                   -- phone or email, free text
  monthly_pledge numeric(12,2) not null default 0 check (monthly_pledge >= 0),
  is_active      boolean not null default true,
  note           text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists donors_active_idx on public.donors (is_active, name);

-- ---------------------------------------------------------------------------
-- What a donor actually gave, in a given month.
--
-- The pledge is what they said; a donation is what arrived. Only donations
-- count toward the fund — a month should never be spent against a promise.
-- ---------------------------------------------------------------------------
create table if not exists public.donations (
  id          uuid primary key default gen_random_uuid(),
  donor_id    uuid not null references public.donors (id) on delete cascade,
  month       date not null,                             -- always the 1st
  amount      numeric(12,2) not null check (amount > 0),
  received_on date not null default current_date,
  note        text,
  recorded_by uuid references public.profiles (id),
  created_at  timestamptz not null default now(),
  -- One row per donor per month: recording the same gift twice would inflate
  -- the fund, and an inflated fund is money the committee thinks it has.
  unique (donor_id, month)
);

create index if not exists donations_month_idx on public.donations (month);

create or replace function public.normalise_donation_month()
returns trigger language plpgsql as $$
begin
  new.month := date_trunc('month', new.month)::date;
  return new;
end $$;

drop trigger if exists donations_normalise on public.donations;
create trigger donations_normalise before insert or update on public.donations
  for each row execute function public.normalise_donation_month();

drop trigger if exists donors_touch on public.donors;
create trigger donors_touch before update on public.donors
  for each row execute function public.touch_updated_at();

alter table public.donors    enable row level security;
alter table public.donations enable row level security;

drop policy if exists "donors admin"    on public.donors;
drop policy if exists "donations admin" on public.donations;

-- Donor records are internal finance, like the budget: staff only. A donor's
-- name and what they give is not something members should be able to read.
create policy "donors admin" on public.donors
  for all using (public.is_admin()) with check (public.is_admin());
create policy "donations admin" on public.donations
  for all using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Budget position, now including what donors gave.
--
-- Replaces the 0006 version. `budget` is still the figure an admin set;
-- `donated` is what arrived; `fund` is the two together and is what
-- `remaining` is measured against.
-- ---------------------------------------------------------------------------
create or replace function public.budget_status(p_month date default current_date)
returns json
language sql
stable
security definer
set search_path = public
as $$
  with m as (
    select date_trunc('month', p_month)::date as start_day,
           (date_trunc('month', p_month) + interval '1 month')::date as end_day
  ),
  spent as (
    select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) as total,
           count(*) as transfers
    from public.fund_requests r, m
    where r.status = 'transferred'
      and r.transferred_at >= m.start_day
      and r.transferred_at <  m.end_day
  ),
  committed as (
    -- approved but not yet paid: money the foundation has promised
    select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) as total
    from public.fund_requests r
    where r.status = 'accepted'
  ),
  given as (
    select coalesce(sum(d.amount), 0) as total, count(*) as donors
    from public.donations d, m
    where d.month = m.start_day
  ),
  base as (
    select coalesce((select b.amount from public.monthly_budgets b, m where b.month = m.start_day), 0)
             as amount
  )
  select case when public.is_admin() then json_build_object(
    'month',      (select start_day from m),
    'budget',     (select amount from base),
    'donated',    (select total from given),
    'donors',     (select donors from given),
    'fund',       (select amount from base) + (select total from given),
    'spent',      (select total from spent),
    'transfers',  (select transfers from spent),
    'committed',  (select total from committed),
    'remaining',  (select amount from base) + (select total from given) - (select total from spent),
    'has_budget', exists (select 1 from public.monthly_budgets b, m where b.month = m.start_day)
                    or (select total from given) > 0
  ) else null end;
$$;

-- ---------------------------------------------------------------------------
-- History, with the same two sources side by side.
-- ---------------------------------------------------------------------------
create or replace function public.budget_history(p_months int default 12)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then coalesce((
    select json_agg(t order by t.month desc) from (
      select
        g.month::date as month,
        coalesce(b.amount, 0) as budget,
        coalesce((
          select sum(d.amount) from public.donations d where d.month = g.month::date
        ), 0) as donated,
        coalesce(b.amount, 0) + coalesce((
          select sum(d.amount) from public.donations d where d.month = g.month::date
        ), 0) as fund,
        coalesce((
          select sum(coalesce(r.amount_approved, r.amount_requested))
          from public.fund_requests r
          where r.status = 'transferred'
            and r.transferred_at >= g.month
            and r.transferred_at <  g.month + interval '1 month'
        ), 0) as spent
      from generate_series(
             date_trunc('month', current_date) - ((greatest(p_months, 1) - 1) || ' months')::interval,
             date_trunc('month', current_date),
             interval '1 month'
           ) as g(month)
      left join public.monthly_budgets b on b.month = g.month::date
    ) t
  ), '[]'::json) else null end;
$$;

-- ---------------------------------------------------------------------------
-- Donors for a month, with what each has given — the table the admin sees.
-- Active donors appear whether or not they have given yet, so a missing
-- donation is visible rather than absent.
-- ---------------------------------------------------------------------------
create or replace function public.donor_month(p_month date default current_date)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then coalesce((
    select json_agg(t order by t.name) from (
      select d.id, d.name, d.contact, d.monthly_pledge, d.is_active, d.note,
             dn.id          as donation_id,
             dn.amount      as given,
             dn.received_on as received_on,
             dn.note        as donation_note
      from public.donors d
      left join public.donations dn
        on dn.donor_id = d.id
       and dn.month = date_trunc('month', p_month)::date
      where d.is_active or dn.id is not null
    ) t
  ), '[]'::json) else null end;
$$;


-- ####################  migrations/0011_family_details.sql  ####################

-- ===========================================================================
-- Family details — the household behind an application.
--
-- Registration captures the person; this captures the circumstances the
-- committee is actually deciding on: who depends on them, what comes in, what
-- goes out. It is filled in by staff, usually at the office with the family in
-- front of them, not by the member on their phone.
--
-- Admin-only in both directions. A member cannot read or write their own row —
-- these are caseworker notes about a household, including whether a father is
-- alive, and the foundation should be able to record them frankly.
-- ===========================================================================

create table if not exists public.family_details (
  -- One household per member, so the profile id is the key.
  user_id             uuid primary key references public.profiles (id) on delete cascade,

  head_name           text,
  father_name         text,
  father_mobile       text,
  father_status       text check (father_status in ('alive', 'deceased')),
  address             text,

  total_members       int check (total_members between 0 and 60),
  male_count          int check (male_count between 0 and 60),
  female_count        int check (female_count between 0 and 60),

  /*
   * The household roll, as [{ name, age, relation }].
   *
   * A table would be more relational, but this is edited as one form: the
   * member count drives how many rows appear and the whole household is saved
   * in a single write. JSONB keeps that atomic — no orphan rows when a count
   * shrinks, no half-saved family.
   */
  members             jsonb not null default '[]'::jsonb,

  -- labour | business | job | pension | other — several can be true at once.
  income_sources      text[] not null default '{}',
  income_source_other text,

  monthly_income      numeric(12,2) check (monthly_income >= 0),
  monthly_expense     numeric(12,2) check (monthly_expense >= 0),
  house_type          text check (house_type in ('own', 'rent')),
  has_bank_account    boolean,

  bill_ke             numeric(12,2) check (bill_ke >= 0),          -- electricity, monthly
  rent                numeric(12,2) check (rent >= 0),
  education_expense   numeric(12,2) check (education_expense >= 0),
  medical_expense     numeric(12,2) check (medical_expense >= 0),

  fund_reason         text,

  updated_by          uuid references public.profiles (id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table public.family_details is
  'Household circumstances, recorded by staff. Never member-writable.';
comment on column public.family_details.members is
  'Array of { name, age, relation }; length follows total_members.';

drop trigger if exists family_details_touch on public.family_details;
create trigger family_details_touch before update on public.family_details
  for each row execute function public.touch_updated_at();

alter table public.family_details enable row level security;

drop policy if exists "family admin" on public.family_details;
create policy "family admin" on public.family_details
  for all using (public.is_admin()) with check (public.is_admin());


-- ####################  migrations/0012_donors_are_members.sql  ####################

-- ===========================================================================
-- Donors are members, and the fund is what they gave.
--
-- Two changes that belong together.
--
-- 1. A donor is a registered member, chosen from the roll rather than typed in.
--    Free text meant "Mohsin" and "Mohsin Raza" could be the same person twice,
--    and nothing tied a donation to an account.
--
-- 2. The month's fund is the donations received in it. The budget can no longer
--    be typed in: a figure somebody set is a promise, and the committee was
--    spending against it. Now the only way the fund goes up is a donor giving.
-- ===========================================================================

alter table public.donors
  add column if not exists user_id uuid references public.profiles (id) on delete cascade;

-- Nullable, and unique only where set: rows that predate this stay as they are
-- rather than being deleted, and the app requires an account for new ones.
create unique index if not exists donors_user_idx
  on public.donors (user_id) where user_id is not null;

comment on column public.donors.user_id is
  'The member giving. Required for anything added after 0012; null on legacy rows.';
comment on column public.donors.name is
  'Display fallback for legacy rows. Linked donors are named by their profile.';

-- Link anything that matches a member exactly; leave the rest alone.
update public.donors d
   set user_id = p.id
  from public.profiles p
 where d.user_id is null
   and lower(btrim(d.name)) = lower(btrim(p.full_name))
   and not exists (select 1 from public.donors o where o.user_id = p.id);

-- ---------------------------------------------------------------------------
-- The fund is the donations. `budget` stays in the payload so old months still
-- report what was once set, but it no longer counts toward anything.
-- ---------------------------------------------------------------------------
create or replace function public.budget_status(p_month date default current_date)
returns json
language sql
stable
security definer
set search_path = public
as $$
  with m as (
    select date_trunc('month', p_month)::date as start_day,
           (date_trunc('month', p_month) + interval '1 month')::date as end_day
  ),
  spent as (
    select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) as total,
           count(*) as transfers
    from public.fund_requests r, m
    where r.status = 'transferred'
      and r.transferred_at >= m.start_day
      and r.transferred_at <  m.end_day
  ),
  committed as (
    select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) as total
    from public.fund_requests r
    where r.status = 'accepted'
  ),
  given as (
    select coalesce(sum(d.amount), 0) as total, count(*) as donors
    from public.donations d, m
    where d.month = m.start_day
  )
  select case when public.is_admin() then json_build_object(
    'month',      (select start_day from m),
    'budget',     coalesce((select b.amount from public.monthly_budgets b, m
                             where b.month = m.start_day), 0),
    'donated',    (select total from given),
    'donors',     (select donors from given),
    'fund',       (select total from given),
    'spent',      (select total from spent),
    'transfers',  (select transfers from spent),
    'committed',  (select total from committed),
    'remaining',  (select total from given) - (select total from spent),
    'has_budget', (select total from given) > 0
  ) else null end;
$$;

create or replace function public.budget_history(p_months int default 12)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then coalesce((
    select json_agg(t order by t.month desc) from (
      select
        g.month::date as month,
        coalesce((
          select sum(d.amount) from public.donations d where d.month = g.month::date
        ), 0) as donated,
        coalesce((
          select sum(d.amount) from public.donations d where d.month = g.month::date
        ), 0) as fund,
        coalesce((
          select sum(coalesce(r.amount_approved, r.amount_requested))
          from public.fund_requests r
          where r.status = 'transferred'
            and r.transferred_at >= g.month
            and r.transferred_at <  g.month + interval '1 month'
        ), 0) as spent
      from generate_series(
             date_trunc('month', current_date) - ((greatest(p_months, 1) - 1) || ' months')::interval,
             date_trunc('month', current_date),
             interval '1 month'
           ) as g(month)
    ) t
  ), '[]'::json) else null end;
$$;

-- ---------------------------------------------------------------------------
-- Donors for a month, named by their account.
-- ---------------------------------------------------------------------------
create or replace function public.donor_month(p_month date default current_date)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then coalesce((
    select json_agg(t order by t.name) from (
      select d.id,
             coalesce(p.full_name, d.name)  as name,
             coalesce(p.mobile, d.contact)  as contact,
             p.id                           as user_id,
             p.email                        as email,
             d.monthly_pledge, d.is_active, d.note,
             dn.id          as donation_id,
             dn.amount      as given,
             dn.received_on as received_on,
             dn.note        as donation_note
      from public.donors d
      left join public.profiles p on p.id = d.user_id
      left join public.donations dn
        on dn.donor_id = d.id
       and dn.month = date_trunc('month', p_month)::date
      where d.is_active or dn.id is not null
    ) t
  ), '[]'::json) else null end;
$$;

-- ---------------------------------------------------------------------------
-- Members who could still be added as donors — the picker's source.
-- Searchable, and already-added members are left out.
-- ---------------------------------------------------------------------------
create or replace function public.donor_candidates(p_query text default '')
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.is_admin() then coalesce((
    select json_agg(t order by t.full_name) from (
      select p.id, p.full_name, p.email, p.mobile, p.city
      from public.profiles p
      where not exists (select 1 from public.donors d where d.user_id = p.id)
        and (
          coalesce(btrim(p_query), '') = ''
          or p.full_name ilike '%' || btrim(p_query) || '%'
          or p.email     ilike '%' || btrim(p_query) || '%'
          or p.mobile    ilike '%' || btrim(p_query) || '%'
        )
      limit 25
    ) t
  ), '[]'::json) else null end;
$$;


-- ####################  migrations/0013_transfer_within_fund.sql  ####################

-- ===========================================================================
-- A transfer cannot exceed the month's fund.
--
-- Until now the portal warned and let it through. It should refuse: the fund is
-- the donations that actually arrived, and paying out more than arrived is not
-- a generous decision, it is an overdraft nobody agreed to. If the committee
-- wants to approve more, the answer is another donation, not a bigger number.
--
-- The rule lives here rather than only in /api/requests/:id so it holds for
-- anything that writes — the native app, a script, or a hand-run UPDATE.
-- ===========================================================================

create or replace function public.check_transfer_within_fund()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  pays_at    timestamptz;
  month_start date;
  month_end   date;
  fund        numeric;
  already     numeric;
  amount      numeric;
  remaining   numeric;
begin
  -- Only the move *into* transferred matters. Editing a note on something
  -- already paid must not be refused because the month has since filled up.
  if new.status <> 'transferred' or old.status = 'transferred' then
    return new;
  end if;

  -- requests_log_status runs before this and stamps transferred_at; fall back
  -- to now() in case the ordering ever changes.
  pays_at     := coalesce(new.transferred_at, now());
  month_start := date_trunc('month', (pays_at at time zone 'Asia/Karachi'))::date;
  month_end   := (month_start + interval '1 month')::date;

  select coalesce(sum(d.amount), 0) into fund
    from public.donations d
   where d.month = month_start;

  -- Everything already paid out of this month, excluding this row.
  select coalesce(sum(coalesce(r.amount_approved, r.amount_requested)), 0) into already
    from public.fund_requests r
   where r.status = 'transferred'
     and r.id <> new.id
     and (r.transferred_at at time zone 'Asia/Karachi') >= month_start
     and (r.transferred_at at time zone 'Asia/Karachi') <  month_end;

  amount    := coalesce(new.amount_approved, new.amount_requested);
  remaining := fund - already;

  if amount > remaining then
    raise exception
      'This transfer is % but only % is left in the % fund. Record more donations first.',
      to_char(amount, 'FM999,999,999'),
      to_char(greatest(remaining, 0), 'FM999,999,999'),
      to_char(month_start, 'Month YYYY')
      using errcode = 'check_violation';
  end if;

  return new;
end $$;

-- After requests_log_status alphabetically, so transferred_at is already set.
drop trigger if exists trg_transfer_within_fund on public.fund_requests;
create trigger trg_transfer_within_fund
  before update on public.fund_requests
  for each row execute function public.check_transfer_within_fund();


-- ####################  migrations/0014_payment_method.sql  ####################

-- ===========================================================================
-- How the money actually left: cash in hand, or a bank transfer.
--
-- The transfer reference already recorded *which* transfer it was, but not
-- how it was made — and a receipt handed to a member has to say. Cash has no
-- bank reference to quote, which is exactly why the two need telling apart.
--
-- Nullable: every transfer made before today was recorded without it, and
-- guessing retrospectively would put a false statement on a receipt. Those
-- print as "—" until somebody who knows sets them.
-- ===========================================================================

alter table public.fund_requests
  add column if not exists payment_method text;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'fund_requests_payment_method_check'
  ) then
    alter table public.fund_requests
      add constraint fund_requests_payment_method_check
      check (payment_method is null or payment_method in ('cash', 'bank'));
  end if;
end $$;

comment on column public.fund_requests.payment_method is
  'How a transferred grant was paid: cash or bank. Null for transfers recorded before this was asked for.';
